# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 29d09c71b68ba83185c9067dedf08748d95419c7152c11a376a0314a96bf922b01bd3907445099e0b467dc94260ceb01de61ca435f7910ed5493ed6f7d4ee4b0

test:
  secret_key_base: 0033bbfefde383d06f8abd2132f58dda6c0c1ab14a490397fe01d03e3f0fbbed040edcc165bd29ad2064a872c07fee7ce962f5a499d4a25b5fa1178250f8dddb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
